In [21]:
from pathlib import Path 
import pandas as pd 

filepath = Path("../data/raw") / "Medicare_IP_Hospitals_by_Provider_and_Service_2024.csv"

df = pd.read_csv(
    filepath,
    dtype = {
        'Rndrng_Prvdr_CCN': str,
        'Rndrng_Prvdr_State_FIPS': str,
        'Rndrng_Prvdr_Zip5': str,
        'DRG_Cd': str
    })

df.shape

(145879, 15)

In [22]:
df.head()

,Rndrng_Prvdr_CCN,Rndrng_Prvdr_Org_Name,Rndrng_Prvdr_City,Rndrng_Prvdr_St,Rndrng_Prvdr_State_FIPS,Rndrng_Prvdr_Zip5,Rndrng_Prvdr_State_Abrvtn,Rndrng_Prvdr_RUCA,Rndrng_Prvdr_RUCA_Desc,DRG_Cd,DRG_Desc,Tot_Dschrgs,Avg_Submtd_Cvrd_Chrg,Avg_Tot_Pymt_Amt,Avg_Mdcr_Pymt_Amt
0,010001,Southeast Health Medical Center,Dothan,1108 Ross Clark Circle,01,36301,AL,2.0,Metropolitan area high commuting: primary flow...,003,ECMO OR TRACHEOSTOMY WITH MV >96 HOURS OR PRIN...,11,738478.636360,103236.272730,91218.181818
1,010001,Southeast Health Medical Center,Dothan,1108 Ross Clark Circle,01,36301,AL,2.0,Metropolitan area high commuting: primary flow...,023,CRANIOTOMY WITH MAJOR DEVICE IMPLANT OR ACUTE ...,23,173562.086960,40220.217391,37634.565217
2,010001,Southeast Health Medical Center,Dothan,1108 Ross Clark Circle,01,36301,AL,2.0,Metropolitan area high commuting: primary flow...,024,CRANIOTOMY WITH MAJOR DEVICE IMPLANT OR ACUTE ...,13,95613.307692,27305.461538,25644.307692
3,010001,Southeast Health Medical Center,Dothan,1108 Ross Clark Circle,01,36301,AL,2.0,Metropolitan area high commuting: primary flow...,025,CRANIOTOMY AND ENDOVASCULAR INTRACRANIAL PROCE...,22,182831.409090,31420.954545,23270.863636
4,010001,Southeast Health Medical Center,Dothan,1108 Ross Clark Circle,01,36301,AL,2.0,Metropolitan area high commuting: primary flow...,038,EXTRACRANIAL PROCEDURES WITH CC,27,111318.555560,12183.925926,10532.222222

In [23]:
df.isna().sum()

Rndrng_Prvdr_CCN             0
Rndrng_Prvdr_Org_Name        0
Rndrng_Prvdr_City            0
Rndrng_Prvdr_St              0
Rndrng_Prvdr_State_FIPS      0
Rndrng_Prvdr_Zip5            0
Rndrng_Prvdr_State_Abrvtn    0
Rndrng_Prvdr_RUCA            0
Rndrng_Prvdr_RUCA_Desc       0
DRG_Cd                       0
DRG_Desc                     0
Tot_Dschrgs                  0
Avg_Submtd_Cvrd_Chrg         0
Avg_Tot_Pymt_Amt             0
Avg_Mdcr_Pymt_Amt            0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145879 entries, 0 to 145878
Data columns (total 15 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Rndrng_Prvdr_CCN           145879 non-null  object
 1   Rndrng_Prvdr_Org_Name      145879 non-null  object
 2   Rndrng_Prvdr_City          145879 non-null  object
 3   Rndrng_Prvdr_St            145879 non-null  object
 4   Rndrng_Prvdr_State_FIPS    145879 non-null  object
 5   Rndrng_Prvdr_Zip5          145879 non-null  object
 6   Rndrng_Prvdr_State_Abrvtn  145879 non-null  object
 7   Rndrng_Prvdr_RUCA          145879 non-null  float64
 8   Rndrng_Prvdr_RUCA_Desc     145879 non-null  object
 9   DRG_Cd                     145879 non-null  object
 10  DRG_Desc                   145879 non-null  object
 11  Tot_Dschrgs                145879 non-null  int64
 12  Avg_Submtd_Cvrd_Chrg       145879 non-null  float64
 13  Avg_Tot_Pymt_Amt           145879 non-null  float64
 14  Avg_Mdcr_Pymt_Amt          145879 non-null  float64
dtypes: float64(4), int64(1), object(10)
memory usage: 16.7+ MB

In [27]:
df.columns = df.columns.str.lower()

df.columns

Index(['rndrng_prvdr_ccn', 'rndrng_prvdr_org_name', 'rndrng_prvdr_city',
       'rndrng_prvdr_st', 'rndrng_prvdr_state_fips', 'rndrng_prvdr_zip5',
       'rndrng_prvdr_state_abrvtn', 'rndrng_prvdr_ruca',
       'rndrng_prvdr_ruca_desc', 'drg_cd', 'drg_desc', 'tot_dschrgs',
       'avg_submtd_cvrd_chrg', 'avg_tot_pymt_amt', 'avg_mdcr_pymt_amt'],
      dtype='object')

In [28]:
df[['tot_dschrgs',
    'avg_submtd_cvrd_chrg', 
    'avg_tot_pymt_amt', 
    'avg_mdcr_pymt_amt']].describe()

,tot_dschrgs,avg_submtd_cvrd_chrg,avg_tot_pymt_amt,avg_mdcr_pymt_amt
count,145879.000000,1.458790e+05,1.458790e+05,1.458790e+05
mean,33.949239,9.636609e+04,1.915132e+04,1.578265e+04
std,50.571682,1.293347e+05,2.267339e+04,1.966287e+04
min,11.000000,2.058385e+03,1.849077e+03,3.868000e+02
25%,14.000000,3.684523e+04,9.057232e+03,7.078129e+03
50%,20.000000,6.161959e+04,1.321742e+04,1.085070e+04
75%,35.000000,1.100423e+05,2.095995e+04,1.725262e+04
max,3400.000000,7.196637e+06,1.443310e+06,1.436668e+06